-- omnisharp lsp config
--require('lspconfig').omnisharp.setup {
--  on_attach = function(_, bufnr)
--    vim.api.nvim_buf_set_option(bufnr, 'omnifunc', 'v:lua.vim.lsp.omnifunc')
--  end,
--  cmd = { "/home/psyhich/.local/share/nvim/lsp_servers/omnisharp/omnisharp/run", "--languageserver" , "--hostPID", tostring(pid) },
--}
